services:
  postgres:
    image: postgres:15-alpine
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - banking-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d banking_db -U banking_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
      image: redis:7-alpine
      container_name: banking-redis
      ports:
        - "6379:6379"
      networks:
        - banking-network
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 10s
        timeout: 3s
        retries: 5
      restart: unless-stopped
      command: redis-server --appendonly yes
      volumes:
        - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  banking-network:
    driver: bridge